name: petitions-api

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - petitions-api
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

library:
  source-dirs:
    - src

executables:
  petitions-api:
    main: exe/Main.hs
    dependencies:
      - petitions-api

dependencies:
  - base
  - text
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
